
version: '2.1'
services:
  docker-registry:
    image: home1oss/docker-proxy:1.10.2-alpine
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    container_name: ${SERVER_NAME:-registry.docker.local}
    hostname: ${SERVER_NAME:-registry.docker.local}
    ports:
    - "80/tcp"
    environment:
    - BACKEND_HOST=${BACKEND_HOST:-nexus3.local}
    - BACKEND_PORT=${BACKEND_PORT:-5000}
    - BASIC_AUTH_PASS=${BASIC_AUTH_PASS:-deployment}
    - BASIC_AUTH_USER=${BASIC_AUTH_USER:-deployment}
    - SERVER_NAME=${SERVER_NAME:-registry.docker.local}

networks:
  default:
    external:
      name: oss-network
